apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      # - op: replace
      #   path: /spec/source/path
      #   value: environments/staging
      - op: add
        path: /spec/source/plugin/env
        value:
          - name: ENV
            value: staging
    target:
      kind: Application
      name: trivy