apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rgarcia89/make-argocd.git
    targetRevision: HEAD
    path: .
    plugin:
      name: make-helm-template
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
