apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rgarcia89/make-argocd.git
    targetRevision: HEAD
    path: .
    plugin:
      name: make-render
  destination:
    server: https://kubernetes.default.svc
    namespace: trivy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Add server-side apply for better performance
  # Add retry strategy for failed syncs
  retry:
    limit: 5
    backoff:
      duration: 5s
      factor: 2
      maxDuration: 3m
